name: Devsecops pipeline

on:
  workflow_dispatch:

jobs:
    # These are Quality Scans with in the integration of the code


  Code-Quality:
    uses: ./.github/workflows/code-quality.yml



  Secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit


  Dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml


  Docker-scan:
    uses: ./.github/workflows/docker-lint.yml



  Test-Scan:
    uses: ./.github/workflows/tests.yml

  # Once all the tests are completed, Go for Build of the application 
  
  build:
    needs: [Code-Quality, Secrets-scan, Dependency-scan, Docker-scan, Test-Scan]
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit


  # Image scan 
  trivy:
    needs: [build]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit

    # CD : Deploy to Production 
  deploy:
    needs: [trivy]
    uses: ./.github/workflows/deploy-to-server.yml
    secrets: inherit