# Name of the workflow. 

name: Greet_Hello

# Condition for running the Workflow 

on: 
  push:
    branches: [main]


# Defining Jobs for the Workflow 

jobs:

  # Defining the jobs and parameters  

  greet:

    # Define where it will runn  (Runner)

    runs-on: ubuntu-latest

    #  Defining the steps in the jobs

    steps:

      # Name of the step and the what is the requested step. 

      - name: Greeting hello to the user 
        run: echo "Hello Guys.."

      - name: Greeting the user with name 
        run: echo "Hello $USER"


  # Second job for the workflow 

  details:

    runs-on: ubuntu-latest

    steps:
      - name: Checking the version of Docker in the system 
        run: docker --version && python --version 